<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FHP.AdminSetup</RootNamespace>
    <AssemblyName>FHP.AdminSetup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FHP.Core\FHP.Core.csproj" />
  </ItemGroup>

</Project>
